apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-storage
spec:
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /data/registry
    server: 10.16.68.247
  persistentVolumeReclaimPolicy: Recycle