apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"services"}}
    mcm.ibm.com/accountID: id-mycluster-account
    mcm.ibm.com/type: System
    openshift.io/sa.scc.mcs: s0:c24,c9
    openshift.io/sa.scc.supplemental-groups: 1000570000/10000
    openshift.io/sa.scc.uid-range: 1000570000/10000
  creationTimestamp: "2020-07-21T16:05:13Z"
  deletionTimestamp: "2020-08-26T15:01:17Z"
  name: services
  resourceVersion: "19621045"
  selfLink: /api/v1/namespaces/services
  uid: bd762af3-b4e7-4232-86c0-6544e3b081d9
spec:
  finalizers:
status:
  conditions:
  - lastTransitionTime: "2020-08-26T15:01:27Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2020-08-26T15:01:27Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2020-08-26T15:01:27Z"
    message: 'Failed to delete all resource types, 7 remaining: object *v1alpha1.ClusterList
      does not implement the protobuf marshalling interface and cannot be encoded
      to a protobuf message, object *v1alpha1.ClusterStatusList does not implement
      the protobuf marshalling interface and cannot be encoded to a protobuf message,
      object *v1alpha1.PlacementBindingList does not implement the protobuf marshalling
      interface and cannot be encoded to a protobuf message, object *v1alpha1.PlacementPolicyList
      does not implement the protobuf marshalling interface and cannot be encoded
      to a protobuf message, object *v1alpha1.ResourceViewList does not implement
      the protobuf marshalling interface and cannot be encoded to a protobuf message,
      object *v1alpha1.WorkList does not implement the protobuf marshalling interface
      and cannot be encoded to a protobuf message, object *v1alpha1.WorkSetList does
      not implement the protobuf marshalling interface and cannot be encoded to a
      protobuf message'
    reason: ContentDeletionFailed
    status: "True"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2020-08-26T15:01:29Z"
    message: All content successfully removed
    reason: ContentRemoved
    status: "False"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2020-08-26T15:01:29Z"
    message: All content-preserving finalizers finished
    reason: ContentHasNoFinalizers
    status: "False"
    type: NamespaceFinalizersRemaining
  phase: Terminating
