apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: cam
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: cam-ibm-cam
    helm.sh/chart: ibm-cam-4.2.1
    release: cam
  name: cam-mongo-pv
  namespace: services
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: rook-ceph-block-internal
  volumeMode: Filesystem
